server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git:
#          uri: file://Users/gibkim/Desktop/Work/git-local-repo
          uri: https://github.com/gibKim/spring-cloud-config.git